Miniconda3/4.10.3
Starting to read...
Traceback (most recent call last):
  File "shorten_occurrence.py", line 52, in <module>
    with DwCAReader(dwca_file_path_big) as dwca:
  File "/bask/projects/v/vjgo8416-amber/conda_envs/gbif-species-trainer-AMI-fork/lib/python3.8/site-packages/dwca/read.py", line 97, in __init__
    self._directory_to_clean, self._working_directory_path = self._extract()
  File "/bask/projects/v/vjgo8416-amber/conda_envs/gbif-species-trainer-AMI-fork/lib/python3.8/site-packages/dwca/read.py", line 448, in _extract
    extracted_dir = self._unzip_or_untar()
  File "/bask/projects/v/vjgo8416-amber/conda_envs/gbif-species-trainer-AMI-fork/lib/python3.8/site-packages/dwca/read.py", line 433, in _unzip_or_untar
    zipfile.ZipFile(self.archive_path, 'r').extractall(tmp_dir)
  File "/bask/projects/v/vjgo8416-amber/conda_envs/gbif-species-trainer-AMI-fork/lib/python3.8/zipfile.py", line 1647, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/bask/projects/v/vjgo8416-amber/conda_envs/gbif-species-trainer-AMI-fork/lib/python3.8/zipfile.py", line 1702, in _extract_member
    shutil.copyfileobj(source, target)
  File "/bask/projects/v/vjgo8416-amber/conda_envs/gbif-species-trainer-AMI-fork/lib/python3.8/shutil.py", line 208, in copyfileobj
    fdst_write(buf)
OSError: [Errno 28] No space left on device
