2022-06-16 07:52:50,021 INFO    MainThread:25697 [wandb_setup.py:_flush():76] Loading settings from /home/mila/a/aditya.jain/.config/wandb/settings
2022-06-16 07:52:50,024 INFO    MainThread:25697 [wandb_setup.py:_flush():76] Loading settings from /home/mila/a/aditya.jain/mothAI/classification_moths/wandb/settings
2022-06-16 07:52:50,026 INFO    MainThread:25697 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2022-06-16 07:52:50,028 INFO    MainThread:25697 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'classification_moths/train_uk.py', 'program': 'train_uk.py'}
2022-06-16 07:52:50,031 INFO    MainThread:25697 [wandb_init.py:_log_setup():428] Logging user logs to /home/mila/a/aditya.jain/mothAI/classification_moths/wandb/run-20220616_075249-pb4ttp9s/logs/debug.log
2022-06-16 07:52:50,035 INFO    MainThread:25697 [wandb_init.py:_log_setup():429] Logging internal logs to /home/mila/a/aditya.jain/mothAI/classification_moths/wandb/run-20220616_075249-pb4ttp9s/logs/debug-internal.log
2022-06-16 07:52:50,037 INFO    MainThread:25697 [wandb_init.py:init():462] calling init triggers
2022-06-16 07:52:50,039 INFO    MainThread:25697 [wandb_init.py:init():466] wandb.init called with sweep_config: {}
config: {}
2022-06-16 07:52:50,042 INFO    MainThread:25697 [wandb_init.py:init():515] starting backend
2022-06-16 07:52:50,044 INFO    MainThread:25697 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-16 07:52:50,096 INFO    MainThread:25697 [backend.py:ensure_launched():217] starting backend process...
2022-06-16 07:52:50,144 INFO    MainThread:25697 [backend.py:ensure_launched():222] started backend process with pid: 25929
2022-06-16 07:52:50,148 INFO    MainThread:25697 [wandb_init.py:init():525] backend started and connected
2022-06-16 07:52:50,484 INFO    MainThread:25697 [wandb_init.py:init():596] updated telemetry
2022-06-16 07:52:50,720 INFO    MainThread:25697 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-06-16 07:53:20,725 INFO    MainThread:25697 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2022-06-16 07:53:20,728 ERROR   MainThread:25697 [wandb_init.py:init():636] backend process timed out
2022-06-16 07:53:20,730 ERROR   MainThread:25697 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-16 07:53:23,951 INFO    MainThread:25697 [wandb_init.py:teardown():276] tearing down wandb.init
